#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : importlib_metadata
Version  : 0.18
Release  : 6
URL      : https://files.pythonhosted.org/packages/fd/5c/9caf9fe3d92afc3c0296c97b0fd72cacfcaf20e8b2c42306840914e052fa/importlib_metadata-0.18.tar.gz
Source0  : https://files.pythonhosted.org/packages/fd/5c/9caf9fe3d92afc3c0296c97b0fd72cacfcaf20e8b2c42306840914e052fa/importlib_metadata-0.18.tar.gz
Summary  : Read metadata from Python packages
Group    : Development/Tools
License  : Apache-2.0
Requires: importlib_metadata-license = %{version}-%{release}
Requires: importlib_metadata-python = %{version}-%{release}
Requires: importlib_metadata-python3 = %{version}-%{release}
Requires: configparser
Requires: contextlib2
Requires: pathlib2
Requires: zipp
BuildRequires : buildreq-distutils3
BuildRequires : configparser
BuildRequires : contextlib2
BuildRequires : pathlib2
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zipp

%description
=========================
``importlib_metadata``
=========================
``importlib_metadata`` is a library to access the metadata for a Python
package.  It is intended to be ported to Python 3.8.

%package license
Summary: license components for the importlib_metadata package.
Group: Default

%description license
license components for the importlib_metadata package.


%package python
Summary: python components for the importlib_metadata package.
Group: Default
Requires: importlib_metadata-python3 = %{version}-%{release}

%description python
python components for the importlib_metadata package.


%package python3
Summary: python3 components for the importlib_metadata package.
Group: Default
Requires: python3-core

%description python3
python3 components for the importlib_metadata package.


%prep
%setup -q -n importlib_metadata-0.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560302379
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/importlib_metadata
cp LICENSE %{buildroot}/usr/share/package-licenses/importlib_metadata/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/importlib_metadata/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
